# Generated by Django 5.2.3 on 2025-07-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquirie', '0002_enquiriesmodel_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiriesmodel',
            name='is_dealer',
            field=models.BooleanField(default=False),
        ),
    ]
