# Generated by Django 5.2.3 on 2025-07-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquirie', '0003_enquiriesmodel_is_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerEnquiries',
            fields=[
            ],
            options={
                'verbose_name': 'Dealer Enquiry',
                'verbose_name_plural': 'Dealer Enquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('enquirie.enquiriesmodel',),
        ),
        migrations.CreateModel(
            name='PublicEnquiries',
            fields=[
            ],
            options={
                'verbose_name': 'Public Enquiry',
                'verbose_name_plural': 'Public Enquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('enquirie.enquiriesmodel',),
        ),
    ]
