# Generated by Django 5.2.3 on 2025-07-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquirie', '0004_dealerenquiries_publicenquiries'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.BigIntegerField(default=0, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('enquiry_date', models.DateTimeField(auto_now_add=True)),
                ('items', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DealerEnquiries',
        ),
        migrations.DeleteModel(
            name='PublicEnquiries',
        ),
    ]
