# Generated by Django 5.2.3 on 2025-07-24 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquirie', '0005_dealerenquiry_delete_dealerenquiries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerenquiry',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerenquiry',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dealerenquiry',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dealerenquiry',
            name='enquiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dealerenquiry',
            name='items',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='dealerenquiry',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
