# Generated by Django 5.2.3 on 2025-07-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquirie', '0006_dealerenquiry_is_verified_dealerenquiry_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerenquiry',
            name='link_name',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
